<?php
/**
 * Unioncorp theme setup.
 *
 * Unioncorp is a block theme: the layout lives in templates/*.html, the design
 * system in theme.json (generated by .dev/build_theme.py), and the sections in
 * patterns/*.php. This file carries only what those cannot express — supports
 * flags, asset enqueues, block styles, pattern categories, and the guards that
 * keep the theme graceful when a plugin it can use is not installed.
 *
 * @package Unioncorp
 */

defined( 'ABSPATH' ) || exit;

define( 'UNIONCORP_VERSION', '1.1.3' );

/**
 * Theme supports.
 */
function unioncorp_setup() {
	load_theme_textdomain( 'unioncorp', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support(
		'custom-logo',
		array(
			'height'      => 48,
			'width'       => 200,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	// style.css is loaded into the editor canvas too, so the components below
	// look the same there as on the front end.
	add_editor_style( 'style.css' );
}
add_action( 'after_setup_theme', 'unioncorp_setup' );

/**
 * Front-end styles.
 */
function unioncorp_enqueue_styles() {
	wp_enqueue_style( 'unioncorp-style', get_stylesheet_uri(), array(), UNIONCORP_VERSION );
}
add_action( 'wp_enqueue_scripts', 'unioncorp_enqueue_styles' );

/**
 * Block style variations.
 *
 * Registered here rather than in theme.json because a style variation needs a
 * label for the editor's Styles panel, and theme.json has nowhere to put one.
 * Each is a class the stylesheet already carries, so a pattern can ask for it
 * by name and an editor can apply it to their own blocks too.
 */
function unioncorp_register_block_styles() {
	$styles = array(
		'core/heading' => array(
			array( 'unioncorp-eyebrow', __( 'Eyebrow', 'unioncorp' ) ),
		),
		'core/group'   => array(
			array( 'unioncorp-card', __( 'Card', 'unioncorp' ) ),
			array( 'unioncorp-panel', __( 'Panel', 'unioncorp' ) ),
		),
		'core/button'  => array(
			array( 'unioncorp-ghost', __( 'Ghost', 'unioncorp' ) ),
		),
		'core/list'    => array(
			array( 'unioncorp-ticks', __( 'Tick list', 'unioncorp' ) ),
		),
	);

	foreach ( $styles as $block => $variations ) {
		foreach ( $variations as $variation ) {
			list( $name, $label ) = $variation;
			register_block_style(
				$block,
				array(
					'name'  => $name,
					'label' => $label,
				)
			);
		}
	}
}
add_action( 'init', 'unioncorp_register_block_styles' );

/**
 * Scroll reveals, figures that count up, and the video popup.
 *
 * Deferred and in the footer: everything the script does is an enhancement, so
 * it never needs to hold up rendering. `unioncorp_enable_scroll_animations`
 * switches off the motion — reveals and counting — and leaves the video popup,
 * which is behaviour rather than decoration.
 *
 * The settings go in as JSON, not through wp_localize_script(), which turns
 * `false` into an empty string that the script would read as "on".
 */
function unioncorp_enqueue_interactions() {
	wp_enqueue_script(
		'unioncorp-interactions',
		get_template_directory_uri() . '/assets/js/interactions.js',
		array(),
		UNIONCORP_VERSION,
		array(
			'in_footer' => true,
			'strategy'  => 'defer',
		)
	);

	wp_add_inline_script(
		'unioncorp-interactions',
		'window.unioncorpMotion = ' . wp_json_encode(
			array(
				'enabled'    => (bool) apply_filters( 'unioncorp_enable_scroll_animations', true ),
				'videoLabel' => __( 'Video', 'unioncorp' ),
				'closeLabel' => __( 'Close video', 'unioncorp' ),
			)
		) . ';',
		'before'
	);
}
add_action( 'wp_enqueue_scripts', 'unioncorp_enqueue_interactions' );

/**
 * Pattern categories.
 *
 * Registered on `init` so the labels are translated, and before patterns/*.php
 * are read, which is what WordPress does with a theme's patterns directory.
 */
function unioncorp_register_pattern_categories() {
	$categories = array(
		'unioncorp-sections' => array(
			'label'       => __( 'Unioncorp: sections', 'unioncorp' ),
			'description' => __( 'Full-width sections for building pages.', 'unioncorp' ),
		),
		'unioncorp-pages'    => array(
			'label'       => __( 'Unioncorp: pages', 'unioncorp' ),
			'description' => __( 'Complete page layouts.', 'unioncorp' ),
		),
	);

	foreach ( $categories as $slug => $args ) {
		register_block_pattern_category( $slug, $args );
	}
}
add_action( 'init', 'unioncorp_register_pattern_categories' );

require get_template_directory() . '/inc/front-page-setup.php';
require get_template_directory() . '/inc/enquiry.php';
require get_template_directory() . '/inc/forms.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/scheme.php';
require get_template_directory() . '/inc/updates.php';
